# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/h/quanched/chipyard"
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /h/quanched/chipyard/.conda-env
source /h/quanched/chipyard/scripts/fix-open-files.sh
